services:
  - type: web
    name: code-snippet-manager-backend
    env: node
    plan: free
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://manojkumar:Manoj%408143@cluster0.0xoc1yz.mongodb.net/code_snippet_manager?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: 288ad2bc3d79d405dee98bcb988cb534bea9d156b9063dace625d2567c3254ddad5556519a0a8d9016a44c83163a4e02a45e1d289477f08701d1afaff624dbdc
      - key: CLOUDINARY_CLOUD_NAME
        value: duhzpjsoo
      - key: CLOUDINARY_API_KEY
        value: 338675644846919
      - key: CLOUDINARY_API_SECRET
        value: vKFbLCvGc6GxFnxujCmgkOOGHpg

  - type: web
    name: code-snippet-manager-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://code-snippet-manager-backend-7v42.onrender.com/api
